# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# [[ Env vars ]]
# my config files
export DOTFILES=$HOME/dotfiles

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache
export XDG_STATE_HOME=$HOME/.local/state

# oh-my-posh
curl -s https://ohmyposh.dev/install.sh | bash -s

# Term
export TERM=xterm-256color

# oh-my-posh
curl -s https://ohmyposh.dev/install.sh | bash -s

# Editor
export EDITOR="nvim"
export VISUAL="nvim"

# FZF stuff
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Bat
export BAT_THEME="gruvbox-dark"

# Go stuff
export GOPATH=$HOME/.go
export GOBIN=$GOPATH/bin # has to be abs or use $GOPATH
export GOMODCACHE=$GOPATH/pkg/mod
export GOCACHE=$XDG_CACHE_HOME/go-build

# Path
ALLPATHS=(
	"$HOME/.local/bin"
	"/usr/local/go/bin"
	"$HOME/.cargo/bin"
	"$GOPATH/bin"
)
printf -v NEWPATHS "%s:" "${ALLPATHS[@]}"
export PATH=${NEWPATHS}${PATH}

export LANG=en_US.UTF-8

# emacs mode
set -o emacs
bind '"\C-p": history-search-backward'
bind '"\C-n": history-search-forward'

# system aliases
alias e='nvim'
alias vi="nvim -u $HOME/.config/nvim/minimal-nvim.lua"
alias less='less -R' # pass escape chars through
alias c='clear'
alias enw='emacs -nw'
alias ls='ls --color=always'
alias h='history | fzf'
# git
alias ga='git add'
alias gd='git diff'
alias gst='git status'
alias gp='git push'
alias gc='git commit'
alias gpo='gp --set-upstream origin $(git rev-parse --abbrev-ref HEAD)'
# tmux
alias tns='tmux new-session -s'
alias tl='tmux list-sessions'
alias ta='tmux attach -t'
# copy and paste commands
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
# fix watch
alias watch="watch "

# remove things like ^M on enter for interactive CLIs
stty sane

# shell integrations
eval "$(fzf --bash)"
eval "$(oh-my-posh init bash --config $DOTFILES/oh-my-posh/term-theme.toml)"
eval "$(direnv hook bash)"
eval "$(zoxide init --cmd cd bash)"
